development:
  :address: smtpout.secureserver.net
  :port: 25
  :authentication: plain
  :user_name: contact
  :password: 
  :enable_starttls_auto: true
production:
  :address: smtpout.secureserver.net
  :port: 25
  :authentication: plain
  :user_name: contact
  :password: 
  :enable_starttls_auto: true