development:
  :address: smtpout.secureserver.net
  :port: 25
  :authentication: plain
  :user_name: contact@gdpproductions.com
  :password: Sark1s!
production:
  :address: smtpout.secureserver.net
  :port: 25
  :authentication: plain
  :user_name: contact@gdpproductions.com
  :password: Sark1s!
